"""Initial migration - create users table

Revision ID: 5f51dce6f468
Revises: 
Create Date: 2024-09-02 12:36:05.094374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f51dce6f468'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_email', sa.String(length=120), nullable=False),
    sa.Column('_order_id', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('_phone_number', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('is_whatsapp_same', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('year_of_graduation', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('accompanied_person', sa.String(length=50), nullable=True),
    sa.Column('parents', sa.Boolean(), nullable=False),
    sa.Column('children', sa.Boolean(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('order_total', sa.Float(), nullable=True),
    sa.Column('contribution_amount', sa.Float(), nullable=True),
    sa.Column('order_status', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("gender IN ('Male', 'Female', 'Other')", name='check_gender'),
    sa.CheckConstraint("order_status IN ('pending', 'completed', 'failed')", name='check_order_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_order_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users__email'), ['_email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users__email'))

    op.drop_table('users')
    # ### end Alembic commands ###
